### ISSUE TITLE
Version problem

### ISSUE THREAD

**Issue by hopheylalaley84** [wh120/flutter_fcm#3]
Because flutter_fcm >=1.0.4 depends on firebase_messaging ^12.0.3 and pryaniconline depends on firebase_messaging ^14.1.3, flutter_fcm >=1.0.4 is forbidden.
So, because pryaniconline depends on flutter_fcm ^1.0.5, version solving failed.
pub get failed (1; So, because pryaniconline depends on flutter_fcm ^1.0.5, version solving failed.)

**Comment by wh120** [comment]
Successfully uploaded https://pub.dev/packages/flutter_fcm version 1.0.6.
