### ISSUE TITLE
IOS Local Notification Issue

### ISSUE THREAD

**Issue by developer-farhan** [wh120/flutter_fcm#5]
Even when I have set local notification OFF from boolean value and even comment the following code out

 ```if (notification != null && android != null && withLocalNotification) {
        LocalNotification.showNotification(
            notification: notification, payload: message.data, icon: icon);
      }```
      


im still getting local notification idk why

**Comment by wh120** [comment]
You can remove notification object from API request at the backend 
like this and remember to add content-available field .
`
{
    "to": "_token",
    "priority": "high",
    "content-available": true,
    "apns-priority": 5,
    "data": {
        "content-available": 1
    }
}
`
